package com.danayapie.SweetLimeTool.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Objects;

@DynamoDBTable(tableName = "SupportedWebsite")
public class SupportedWebsite {

    @DynamoDBHashKey(attributeName = "WebId")
    @DynamoDBAutoGeneratedKey
    private String webId;

    @DynamoDBAttribute(attributeName = "DomainName")
    private String domainName;

    @DynamoDBAttribute(attributeName = "CreatedDate")
    private long createdDate;

    public SupportedWebsite() {
    }

    public SupportedWebsite(String webId, String domainName, long createdDate) {
        this.webId = webId;
        this.domainName = domainName;
        this.createdDate = createdDate;
    }

    public String getWebId() {
        return webId;
    }

    public void setWebId(String webId) {
        this.webId = webId;
    }

    public String getDomainName() {
        return domainName;
    }

    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }

    public long getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(long createdDate) {
        this.createdDate = createdDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SupportedWebsite)) return false;
        SupportedWebsite that = (SupportedWebsite) o;
        return Objects.equals(webId, that.webId) && Objects.equals(domainName, that.domainName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(webId, domainName);
    }

    @Override
    public String toString() {
        return "SupportedWebsite{" +
                "webId='" + webId + '\'' +
                ", domainName='" + domainName + '\'' +
                ", createdDate=" + createdDate +
                '}';
    }
}