package com.danayapie.SweetLimeWebService.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.List;
import java.util.Map;
import java.util.Objects;

@DynamoDBTable(tableName = "Product")
public class Product {

    @DynamoDBHashKey(attributeName = "ProductId")
    @DynamoDBAutoGeneratedKey
    private String ProductId;

    @DynamoDBAttribute(attributeName = "WebId")
    private SupportedWebsite WebId;

    @DynamoDBAttribute(attributeName = "ProductName")
    private String ProductName;

    @DynamoDBAttribute(attributeName = "ProductUrl")
    private String ProductUrl;

    @DynamoDBAttribute(attributeName = "Options")
    private Map<String, String> Options;

    @DynamoDBAttribute(attributeName = "PriceHistory")
    private List<Map<String, Integer>> PriceHistory;

    @DynamoDBAttribute(attributeName = "ImageLocation")
    private String ImageLocation;

    @DynamoDBAttribute(attributeName = "CreatedDate")
    private int CreatedDate;

    @DynamoDBAttribute(attributeName = "DeletedDate")
    private int DeletedDate;

    public Product() {
    }

    public Product(String productId, SupportedWebsite webId, String productName, String productUrl, Map<String, String> options, List<Map<String, Integer>> priceHistory, String imageLocation, int createdDate, int deletedDate) {
        ProductId = productId;
        WebId = webId;
        ProductName = productName;
        ProductUrl = productUrl;
        Options = options;
        PriceHistory = priceHistory;
        ImageLocation = imageLocation;
        CreatedDate = createdDate;
        DeletedDate = deletedDate;
    }

    public String getProductId() {
        return ProductId;
    }

    public void setProductId(String productId) {
        ProductId = productId;
    }

    public SupportedWebsite getWebId() {
        return WebId;
    }

    public void setWebId(SupportedWebsite webId) {
        WebId = webId;
    }

    public String getProductName() {
        return ProductName;
    }

    public void setProductName(String productName) {
        ProductName = productName;
    }

    public String getProductUrl() {
        return ProductUrl;
    }

    public void setProductUrl(String productUrl) {
        ProductUrl = productUrl;
    }

    public Map<String, String> getOptions() {
        return Options;
    }

    public void setOptions(Map<String, String> options) {
        Options = options;
    }

    public List<Map<String, Integer>> getPriceHistory() {
        return PriceHistory;
    }

    public void setPriceHistory(List<Map<String, Integer>> priceHistory) {
        PriceHistory = priceHistory;
    }

    public String getImageLocation() {
        return ImageLocation;
    }

    public void setImageLocation(String imageLocation) {
        ImageLocation = imageLocation;
    }

    public int getCreatedDate() {
        return CreatedDate;
    }

    public void setCreatedDate(int createdDate) {
        CreatedDate = createdDate;
    }

    public int getDeletedDate() {
        return DeletedDate;
    }

    public void setDeletedDate(int deletedDate) {
        DeletedDate = deletedDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Product)) return false;
        Product product = (Product) o;
        return Objects.equals(ProductId, product.ProductId) && Objects.equals(WebId, product.WebId) && Objects.equals(ProductName, product.ProductName) && Objects.equals(ProductUrl, product.ProductUrl) && Objects.equals(Options, product.Options);
    }

    @Override
    public int hashCode() {
        return Objects.hash(ProductId, WebId, ProductName, ProductUrl, Options);
    }

    @Override
    public String toString() {
        return "Product{" +
                "ProductId='" + ProductId + '\'' +
                ", WebId=" + WebId +
                ", ProductName='" + ProductName + '\'' +
                ", ProductUrl='" + ProductUrl + '\'' +
                ", Options=" + Options +
                ", PriceHistory=" + PriceHistory +
                ", ImageLocation='" + ImageLocation + '\'' +
                ", CreatedDate=" + CreatedDate +
                ", DeletedDate=" + DeletedDate +
                '}';
    }
}
