package com.danayapie.SweetLimeWebService.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Objects;

@DynamoDBTable(tableName = "SupportedWebsite")
public class SupportedWebsite {

    @DynamoDBHashKey(attributeName = "WebId")
    @DynamoDBAutoGeneratedKey
    private String webId;

    @DynamoDBAttribute(attributeName = "WebName")
    private String webName;

    @DynamoDBAttribute(attributeName = "WebUrl")
    private String webUrl;

    @DynamoDBAttribute(attributeName = "CreatedDate")
    private long createdDate;

    public SupportedWebsite() {
    }

    public SupportedWebsite(String webId, String webName, String webUrl, long createdDate) {
        this.webId = webId;
        this.webName = webName;
        this.webUrl = webUrl;
        this.createdDate = createdDate;
    }

    public String getWebId() {
        return webId;
    }

    public void setWebId(String webId) {
        this.webId = webId;
    }

    public String getWebName() {
        return webName;
    }

    public void setWebName(String webName) {
        this.webName = webName;
    }

    public String getWebUrl() {
        return webUrl;
    }

    public void setWebUrl(String webUrl) {
        this.webUrl = webUrl;
    }

    public long getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(long createdDate) {
        this.createdDate = createdDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SupportedWebsite)) return false;
        SupportedWebsite that = (SupportedWebsite) o;
        return Objects.equals(webId, that.webId) && Objects.equals(webName, that.webName) && Objects.equals(webUrl, that.webUrl);
    }

    @Override
    public int hashCode() {
        return Objects.hash(webId, webName, webUrl);
    }

    @Override
    public String toString() {
        return "SupportedWebsite{" +
                "webId='" + webId + '\'' +
                ", webName='" + webName + '\'' +
                ", webUrl='" + webUrl + '\'' +
                ", createdDate=" + createdDate +
                '}';
    }
}
