package com.danayapie.SweetLimeWebService.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Objects;

@DynamoDBTable(tableName = "SupportedWebsite")
public class SupportedWebsite {

    @DynamoDBHashKey(attributeName = "WebId")
    @DynamoDBAutoGeneratedKey
    private String WebId;

    @DynamoDBAttribute(attributeName = "WebName")
    private String WebName;

    @DynamoDBAttribute(attributeName = "WebUrl")
    private String WebUrl;

    public SupportedWebsite() {
    }

    public SupportedWebsite(String webId, String webName, String webUrl) {
        WebId = webId;
        WebName = webName;
        WebUrl = webUrl;
    }

    public String getWebId() {
        return WebId;
    }

    public void setWebId(String webId) {
        WebId = webId;
    }

    public String getWebName() {
        return WebName;
    }

    public void setWebName(String webName) {
        WebName = webName;
    }

    public String getWebUrl() {
        return WebUrl;
    }

    public void setWebUrl(String webUrl) {
        WebUrl = webUrl;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SupportedWebsite)) return false;
        SupportedWebsite that = (SupportedWebsite) o;
        return Objects.equals(WebId, that.WebId) && Objects.equals(WebName, that.WebName) && Objects.equals(WebUrl, that.WebUrl);
    }

    @Override
    public int hashCode() {
        return Objects.hash(WebId, WebName, WebUrl);
    }

    @Override
    public String toString() {
        return "SupportedWebsite{" +
                "WebId='" + WebId + '\'' +
                ", WebName='" + WebName + '\'' +
                ", WebUrl='" + WebUrl + '\'' +
                '}';
    }
}
